id: IFC85B8D9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:55:18+00:00'
last_modified: '2022-06-08T08:41:37.548561+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG2740
  title: པེནཐོཨུསེ་ཨོཕ༹་ཐེ་གོདས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E27A:
      image_group_id: I1KG2744
      title: ''
      total_pages: 427
      order: 1
      base_file: E27A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
