id: IFC85B8D9
legacy_id: P009110
ocr_import_info:
  bdrc_scan_id: W1KG2740
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T03:52:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:53:21.853606+00:00'
last_modified: 2022-08-31 22:53:43.837105
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG2740
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG2740
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: penthouse of the gods
  author: bernard, theos
statistics:
  ocr_word_mean_confidence_index: 0.9848906936331527
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG2744:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2744
      total_pages: 427
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG2744.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9848906936331527
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
